-- +goose Up
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS library;
CREATE SCHEMA IF NOT EXISTS jobs;

-- +goose Down
DROP SCHEMA IF EXISTS jobs CASCADE;
DROP SCHEMA IF EXISTS library CASCADE;
DROP SCHEMA IF EXISTS catalog CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
