-- +goose Up

CREATE TABLE catalog.games (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            text        NOT NULL UNIQUE,
    title           text        NOT NULL,
    summary         text,
    description     text,
    release_date    date,
    game_type       text        NOT NULL CHECK (game_type IN (
                        'main_game', 'dlc', 'expansion', 'standalone_expansion',
                        'remaster', 'remake', 'edition', 'bundle'
                    )),
    parent_game_id  bigint      REFERENCES catalog.games (id),
    franchise_id    int,
    series_id       int,
    cover_image_url text,
    deleted_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX catalog_games_release_date_idx ON catalog.games (release_date);
CREATE INDEX catalog_games_parent_game_id_idx ON catalog.games (parent_game_id);
CREATE INDEX catalog_games_franchise_id_idx ON catalog.games (franchise_id);
CREATE INDEX catalog_games_series_id_idx ON catalog.games (series_id);

CREATE TRIGGER catalog_games_set_updated_at
    BEFORE UPDATE ON catalog.games
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE catalog.platforms (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

CREATE TABLE catalog.genres (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

CREATE TABLE catalog.companies (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

CREATE TABLE catalog.franchises (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

CREATE TABLE catalog.series (
    id           int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text NOT NULL,
    slug         text NOT NULL UNIQUE,
    franchise_id int  REFERENCES catalog.franchises (id)
);

ALTER TABLE catalog.games
    ADD CONSTRAINT catalog_games_franchise_id_fkey FOREIGN KEY (franchise_id) REFERENCES catalog.franchises (id),
    ADD CONSTRAINT catalog_games_series_id_fkey FOREIGN KEY (series_id) REFERENCES catalog.series (id);

CREATE TABLE catalog.game_platforms (
    game_id     bigint NOT NULL REFERENCES catalog.games (id) ON DELETE CASCADE,
    platform_id int    NOT NULL REFERENCES catalog.platforms (id),
    PRIMARY KEY (game_id, platform_id)
);

CREATE INDEX catalog_game_platforms_platform_id_idx ON catalog.game_platforms (platform_id);

CREATE TABLE catalog.game_genres (
    game_id  bigint NOT NULL REFERENCES catalog.games (id) ON DELETE CASCADE,
    genre_id int    NOT NULL REFERENCES catalog.genres (id),
    PRIMARY KEY (game_id, genre_id)
);

CREATE INDEX catalog_game_genres_genre_id_idx ON catalog.game_genres (genre_id);

CREATE TABLE catalog.game_companies (
    game_id    bigint NOT NULL REFERENCES catalog.games (id) ON DELETE CASCADE,
    company_id int    NOT NULL REFERENCES catalog.companies (id),
    role       text   NOT NULL CHECK (role IN ('developer', 'publisher')),
    PRIMARY KEY (game_id, company_id, role)
);

CREATE INDEX catalog_game_companies_company_role_idx ON catalog.game_companies (company_id, role);

CREATE TABLE catalog.external_game_ids (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id     bigint NOT NULL REFERENCES catalog.games (id) ON DELETE CASCADE,
    provider    text   NOT NULL CHECK (provider IN ('igdb', 'steam', 'psn', 'xbox')),
    provider_id text   NOT NULL
);

CREATE UNIQUE INDEX catalog_external_game_ids_provider_key
    ON catalog.external_game_ids (provider, provider_id);
CREATE INDEX catalog_external_game_ids_game_id_idx ON catalog.external_game_ids (game_id);

CREATE TABLE catalog.game_media (
    id         bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    bigint  NOT NULL REFERENCES catalog.games (id) ON DELETE CASCADE,
    media_type text    NOT NULL CHECK (media_type IN ('cover', 'screenshot', 'artwork', 'backdrop')),
    url        text    NOT NULL,
    position   integer NOT NULL DEFAULT 0
);

CREATE INDEX catalog_game_media_game_media_type_position_idx
    ON catalog.game_media (game_id, media_type, position);

-- +goose Down
DROP TABLE IF EXISTS catalog.game_media;
DROP TABLE IF EXISTS catalog.external_game_ids;
DROP TABLE IF EXISTS catalog.game_companies;
DROP TABLE IF EXISTS catalog.game_genres;
DROP TABLE IF EXISTS catalog.game_platforms;
ALTER TABLE catalog.games
    DROP CONSTRAINT IF EXISTS catalog_games_franchise_id_fkey,
    DROP CONSTRAINT IF EXISTS catalog_games_series_id_fkey;
DROP TABLE IF EXISTS catalog.series;
DROP TABLE IF EXISTS catalog.franchises;
DROP TABLE IF EXISTS catalog.companies;
DROP TABLE IF EXISTS catalog.genres;
DROP TABLE IF EXISTS catalog.platforms;
DROP TABLE IF EXISTS catalog.games;
